import Foundation
import AppKit
import os.log

private let log = OSLog(subsystem: "com.wadesellers.matrix", category: "idle")

/// Tracks user idle time by listening for real input events (`NSEvent`
/// global + local monitors) and emits a callback when the configured
/// threshold is reached.
///
/// Why not `IOHIDSystem.HIDIdleTime`? On many Macs that counter gets
/// reset every ~10 seconds by phantom HID events generated by Bluetooth
/// peripherals, Apple Watch unlock probes, screen-sharing utilities,
/// power-management heartbeats, etc. — so the system idle never crosses
/// any reasonable threshold. Using `NSEvent` monitors means we only see
/// real input (mouse, scroll, gestures), which is enough.
@MainActor
final class IdleMonitor {
    /// Seconds of inactivity required before firing.
    var thresholdSeconds: TimeInterval

    /// Called on the main thread when the threshold is first crossed.
    /// Won't fire again until the user is active, then idle again.
    var onIdle: (() -> Void)?

    /// When false, the monitor stops polling AND stops listening for
    /// events. Set to false while a Matrix session is already showing.
    var isEnabled: Bool = true {
        didSet {
            guard isEnabled != oldValue else { return }
            if isEnabled { start() } else { stop() }
        }
    }

    private var pollTimer: Timer?
    private var globalEventMonitor: Any?
    private var localEventMonitor: Any?
    private var hasFiredForCurrentIdlePeriod: Bool = false

    /// Monotonic timestamp of the last user input event, in
    /// `ProcessInfo.systemUptime` seconds. Updated from the `NSEvent`
    /// monitors. Initial value = "right now" so we don't false-fire on
    /// the first tick after start().
    private var lastInputTime: TimeInterval = ProcessInfo.processInfo.systemUptime

    init(thresholdSeconds: TimeInterval = 5 * 60) {
        self.thresholdSeconds = thresholdSeconds
    }

    func start() {
        stop()
        os_log("idle monitor START threshold=%{public}.1fs",
               log: log, type: .info, thresholdSeconds)
        // Reset baseline so we don't immediately fire from a long-stale
        // lastInputTime captured before the user enabled idle activation.
        lastInputTime = ProcessInfo.processInfo.systemUptime

        // Mouse, scroll, gesture events. We deliberately do NOT include
        // keyboard events (which would require Accessibility permission)
        // — typing is rarely the only signal of activity, and avoiding
        // the system permission dialog is worth the slight loosening
        // of the idle definition.
        let mask: NSEvent.EventTypeMask = [
            .mouseMoved,
            .leftMouseDown, .rightMouseDown, .otherMouseDown,
            .leftMouseDragged, .rightMouseDragged,
            .scrollWheel,
            .magnify, .swipe, .rotate,
        ]

        // Global: events delivered to other apps. We see them, can't
        // modify them.
        globalEventMonitor = NSEvent.addGlobalMonitorForEvents(matching: mask) { [weak self] _ in
            Task { @MainActor in self?.markActive() }
        }
        // Local: events delivered to our own app (settings window, etc.).
        // Returning the event passes it through unchanged.
        localEventMonitor = NSEvent.addLocalMonitorForEvents(matching: mask) { [weak self] event in
            Task { @MainActor in self?.markActive() }
            return event
        }

        // Periodic check against threshold.
        let timer = Timer.scheduledTimer(
            withTimeInterval: 1.0,
            repeats: true
        ) { [weak self] _ in
            Task { @MainActor in self?.tick() }
        }
        RunLoop.main.add(timer, forMode: .common)
        pollTimer = timer
    }

    func stop() {
        pollTimer?.invalidate()
        pollTimer = nil
        if let m = globalEventMonitor {
            NSEvent.removeMonitor(m)
            globalEventMonitor = nil
        }
        if let m = localEventMonitor {
            NSEvent.removeMonitor(m)
            localEventMonitor = nil
        }
    }

    /// Reset edge-trigger state — call when the user has dismissed the
    /// screensaver (we're no longer in the "fired" state).
    func resetEdgeTrigger() {
        hasFiredForCurrentIdlePeriod = false
        lastInputTime = ProcessInfo.processInfo.systemUptime
    }

    private func markActive() {
        lastInputTime = ProcessInfo.processInfo.systemUptime
        // Real input arrived → user is no longer idle, allow next idle
        // period to fire again.
        hasFiredForCurrentIdlePeriod = false
    }

    private func tick() {
        let idle = ProcessInfo.processInfo.systemUptime - lastInputTime
        if idle >= thresholdSeconds, !hasFiredForCurrentIdlePeriod {
            hasFiredForCurrentIdlePeriod = true
            os_log("FIRED — calling onIdle (idle=%{public}.1fs)",
                   log: log, type: .info, idle)
            onIdle?()
        }
    }
}
