import Foundation
import AppKit
import ApplicationServices
import os.log

private let log = OSLog(subsystem: "com.wadesellers.matrix", category: "idle")

/// Tracks user idle time by listening for real input events (`NSEvent`
/// global + local monitors) and emits a callback when the configured
/// threshold is reached.
///
/// Why not `IOHIDSystem.HIDIdleTime`? On many Macs that counter gets
/// reset every ~10 seconds by phantom HID events generated by Bluetooth
/// peripherals, Apple Watch unlock probes, screen-sharing utilities,
/// power-management heartbeats, etc. — so the system idle never crosses
/// any reasonable threshold. The user is genuinely not interacting,
/// but the kernel-level counter says they are.
///
/// Using `NSEvent` global/local monitors instead means we only see real
/// input: mouse moves, mouse-button events, scroll wheel, gestures, and
/// — once the user grants Accessibility — keyboard events too. We prompt
/// for Accessibility on first `start()`. If the user denies, the mask
/// still lists keyboard events; macOS just won't deliver them, and we
/// fall back gracefully to mouse/scroll/gesture detection.
@MainActor
final class IdleMonitor {
    /// Seconds of inactivity required before firing.
    var thresholdSeconds: TimeInterval

    /// Called on the main thread when the threshold is first crossed.
    /// Won't fire again until the user is active, then idle again.
    var onIdle: (() -> Void)?

    /// When false, the monitor stops polling AND stops listening for
    /// events. Set to false while a Matrix session is already showing.
    var isEnabled: Bool = true {
        didSet {
            guard isEnabled != oldValue else { return }
            if isEnabled { start() } else { stop() }
        }
    }

    private var pollTimer: Timer?
    private var globalEventMonitor: Any?
    private var localEventMonitor: Any?
    private var hasFiredForCurrentIdlePeriod: Bool = false
    private var hasPromptedForAccessibility: Bool = false

    /// Monotonic timestamp of the last user input event, in
    /// `ProcessInfo.systemUptime` seconds. Updated from the `NSEvent`
    /// monitors. Initial value = "right now" so we don't false-fire on
    /// the first tick after start().
    private var lastInputTime: TimeInterval = ProcessInfo.processInfo.systemUptime

    init(thresholdSeconds: TimeInterval = 5 * 60) {
        self.thresholdSeconds = thresholdSeconds
    }

    func start() {
        stop()
        os_log("idle monitor START threshold=%{public}.1fs",
               log: log, type: .info, thresholdSeconds)
        // Reset baseline so we don't immediately fire from a long-stale
        // lastInputTime captured before the user enabled idle activation.
        lastInputTime = ProcessInfo.processInfo.systemUptime

        // First start gets the Accessibility prompt so we can also see
        // keyboard input. If denied, the rest of the events still flow.
        requestAccessibilityIfNeeded()

        // Watch real input events. Keyboard events only deliver if the
        // user granted Accessibility — including them in the mask is safe
        // either way (macOS just no-ops them when we're not trusted).
        let mask: NSEvent.EventTypeMask = [
            .mouseMoved,
            .leftMouseDown, .rightMouseDown, .otherMouseDown,
            .leftMouseDragged, .rightMouseDragged,
            .scrollWheel,
            .magnify, .swipe, .rotate,
            .keyDown, .keyUp, .flagsChanged
        ]

        // Global: events delivered to other apps. We see them, can't
        // modify them.
        globalEventMonitor = NSEvent.addGlobalMonitorForEvents(matching: mask) { [weak self] _ in
            Task { @MainActor in self?.markActive() }
        }
        // Local: events delivered to our own app (settings window, etc.).
        // Returning the event passes it through unchanged.
        localEventMonitor = NSEvent.addLocalMonitorForEvents(matching: mask) { [weak self] event in
            Task { @MainActor in self?.markActive() }
            return event
        }

        // Periodic check against threshold.
        let timer = Timer.scheduledTimer(
            withTimeInterval: 1.0,
            repeats: true
        ) { [weak self] _ in
            Task { @MainActor in self?.tick() }
        }
        RunLoop.main.add(timer, forMode: .common)
        pollTimer = timer
    }

    func stop() {
        pollTimer?.invalidate()
        pollTimer = nil
        if let m = globalEventMonitor {
            NSEvent.removeMonitor(m)
            globalEventMonitor = nil
        }
        if let m = localEventMonitor {
            NSEvent.removeMonitor(m)
            localEventMonitor = nil
        }
    }

    /// Reset edge-trigger state — call when the user has dismissed the
    /// screensaver (we're no longer in the "fired" state).
    func resetEdgeTrigger() {
        hasFiredForCurrentIdlePeriod = false
        lastInputTime = ProcessInfo.processInfo.systemUptime
    }

    private func markActive() {
        lastInputTime = ProcessInfo.processInfo.systemUptime
        // Real input arrived → user is no longer idle, allow next idle
        // period to fire again.
        hasFiredForCurrentIdlePeriod = false
    }

    /// Show the system "grant Accessibility" dialog the first time the
    /// monitor starts. Prompting again is harmless — the dialog
    /// suppresses itself if it has already been shown — but we gate it
    /// to one call per app launch to keep the logs tidy.
    ///
    /// macOS won't deliver global keyboard events to `NSEvent` monitors
    /// without this trust. Mouse / scroll / gesture events flow either
    /// way, so denial just means a slightly looser idle definition.
    private func requestAccessibilityIfNeeded() {
        guard !hasPromptedForAccessibility else { return }
        hasPromptedForAccessibility = true

        // Bypass Swift 6's complaint about reading the non-Sendable
        // global `kAXTrustedCheckOptionPrompt`: the constant's value is
        // documented as the literal string below, so we hardcode it.
        let options = ["AXTrustedCheckOptionPrompt": true] as CFDictionary
        let trusted = AXIsProcessTrustedWithOptions(options)

        if trusted {
            os_log("Accessibility granted — keyboard events will be monitored",
                   log: log, type: .info)
        } else {
            os_log("Accessibility NOT granted — running with mouse/scroll/gesture only. Grant in System Settings → Privacy & Security → Accessibility, then quit + relaunch Matrix.",
                   log: log, type: .info)
        }
    }

    private func tick() {
        let idle = ProcessInfo.processInfo.systemUptime - lastInputTime
        os_log("tick idle=%{public}.1fs threshold=%{public}.1fs fired=%{public}@",
               log: log, type: .info,
               idle, thresholdSeconds, hasFiredForCurrentIdlePeriod ? "yes" : "no")

        if idle >= thresholdSeconds, !hasFiredForCurrentIdlePeriod {
            hasFiredForCurrentIdlePeriod = true
            os_log("FIRED — calling onIdle", log: log, type: .info)
            onIdle?()
        }
    }
}
